# Generated by Django 3.1.13 on 2022-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220214_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('transgender', 'transgender'), ('woman', 'Female'), ('man', 'Male'), ('gay', 'gay')], max_length=40),
        ),
    ]
