# Generated by Django 3.1.13 on 2022-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220215_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='text',
            field=models.TextField(default='특이사항: '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200),
        ),
    ]
