# Generated by Django 3.1.13 on 2022-02-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_auto_20220219_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='update',
            new_name='updated',
        ),
    ]
