# Generated by Django 3.1.13 on 2022-02-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0008_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
