# Generated by Django 3.1.13 on 2022-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220214_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('man', 'Male'), ('gay', 'gay'), ('woman', 'Female'), ('transgender', 'transgender')], max_length=40),
        ),
    ]
