# Generated by Django 3.1.13 on 2022-02-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220214_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('gay', 'gay'), ('transgender', 'transgender'), ('woman', 'Female'), ('man', 'Male')], max_length=40),
        ),
    ]
