# Generated by Django 3.1.13 on 2022-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220215_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('man', 'Male'), ('woman', 'Female'), ('gay', 'gay'), ('transgender', 'transgender')], max_length=40),
        ),
    ]
