# Generated by Django 3.1.13 on 2022-02-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_auto_20220217_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='update',
            new_name='updated',
        ),
    ]
