# Generated by Django 3.1.13 on 2022-02-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20220217_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
