# Generated by Django 3.1.13 on 2022-02-13 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('text', models.TextField(default='introduce your self', max_length=100)),
                ('email', models.EmailField(default='@', max_length=50)),
                ('gender', models.CharField(choices=[('woman', 'Female'), ('man', 'Male')], max_length=20)),
                ('Join_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='coustomer',
        ),
    ]
