# Generated by Django 3.1.13 on 2022-02-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220214_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('gay', 'gay'), ('woman', 'Female'), ('transgender', 'transgender'), ('man', 'Male')], max_length=40),
        ),
    ]
