# Generated by Django 3.1.13 on 2022-02-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220214_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('woman', 'Female'), ('man', 'Male'), ('gay', 'gay'), ('transgender', 'transgender')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='text',
            field=models.TextField(default='customer info:', max_length=100),
        ),
    ]
