# Generated by Django 3.1.13 on 2022-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220215_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('transgender', 'transgender'), ('gay', 'gay'), ('woman', 'Female'), ('man', 'Male')], max_length=40),
        ),
    ]
