# Generated by Django 3.1.13 on 2022-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220215_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('woman', 'Female'), ('transgender', 'transgender'), ('gay', 'gay'), ('man', 'Male')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
