# Generated by Django 3.1.13 on 2022-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220215_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('gay', 'gay'), ('man', 'Male'), ('woman', 'Female'), ('transgender', 'transgender')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='customer_', max_length=20),
        ),
    ]
