# Generated by Django 3.1.13 on 2022-02-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220215_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('woman', 'Female'), ('transgender', 'transgender'), ('man', 'Male'), ('gay', 'gay')], max_length=40),
        ),
    ]
